-- Catalogue de valeurs nutritionnelles moyennes par (ingredient, unite),
-- meme forme que prix_moyen_ingredient (V1/V2) : ce sont les valeurs pour
-- 1 GRAMME / 1 MILLILITRE / 1 UNITE de l'ingredient, a multiplier par la
-- quantite d'une ligne d'ingredient pour obtenir sa contribution au repas
-- (voir JpaEstimationNutritionAdapter).
--
-- Estimation manuelle a partir de valeurs nutritionnelles usuelles pour
-- 100g/100ml (ou par piece pour les UNITE), a affiner plus tard — meme
-- demarche que prix_moyen_ingredient. Couvre exactement les memes couples
-- (ingredient, unite) que celui-ci (V2 + V3 + V4), pour que chaque repas du
-- catalogue puisse etre chiffre sans exception.

CREATE TABLE valeur_nutritionnelle_ingredient (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingredient_nom  VARCHAR(255)   NOT NULL,
    unite           VARCHAR(20)    NOT NULL,
    calories        NUMERIC(10, 4) NOT NULL,
    proteines       NUMERIC(10, 4) NOT NULL,
    glucides        NUMERIC(10, 4) NOT NULL,
    lipides         NUMERIC(10, 4) NOT NULL,
    fibres          NUMERIC(10, 4) NOT NULL,
    CONSTRAINT uk_valeur_nutritionnelle_ingredient_nom_unite UNIQUE (ingredient_nom, unite)
);

-- =====================================================================
-- V2 : petits-dejeuners et dejeuners NORMAL/DEBUTANT
-- =====================================================================

INSERT INTO valeur_nutritionnelle_ingredient (ingredient_nom, unite, calories, proteines, glucides, lipides, fibres) VALUES
    ('pain',              'GRAMME',     2.6500, 0.0900, 0.4900, 0.0320, 0.0270),
    ('beurre',            'GRAMME',     7.1700, 0.0090, 0.0010, 0.8100, 0.0000),
    ('confiture',         'GRAMME',     2.5000, 0.0030, 0.6200, 0.0010, 0.0100),
    ('cereales',          'GRAMME',     3.8000, 0.0700, 0.8400, 0.0100, 0.0300),
    ('lait',              'MILLILITRE', 0.6400, 0.0320, 0.0480, 0.0360, 0.0000),
    ('yaourt',            'UNITE',      90.0000, 4.5000, 6.0000, 5.0000, 0.0000),
    ('banane',            'UNITE',      105.0000, 1.3000, 27.0000, 0.3000, 3.1000),
    ('oeufs',             'UNITE',      70.0000, 6.0000, 0.5000, 5.0000, 0.0000),
    ('pain au chocolat',  'UNITE',      280.0000, 5.0000, 30.0000, 15.0000, 1.5000),
    ('jus d''orange',     'MILLILITRE', 0.4500, 0.0070, 0.1000, 0.0020, 0.0020),
    ('pates',             'GRAMME',     3.7100, 0.1300, 0.7500, 0.0150, 0.0300),
    ('thon',              'UNITE',      120.0000, 26.0000, 0.0000, 1.0000, 0.0000),
    ('tomate',            'GRAMME',     0.1800, 0.0090, 0.0390, 0.0020, 0.0120),
    ('riz',               'GRAMME',     3.6000, 0.0700, 0.7800, 0.0060, 0.0130),
    ('poulet',            'GRAMME',     1.6500, 0.3100, 0.0000, 0.0360, 0.0000),
    ('salade',            'GRAMME',     0.1500, 0.0140, 0.0290, 0.0020, 0.0130),
    ('jambon',            'UNITE',      30.0000, 5.0000, 0.2000, 1.0000, 0.0000),
    ('steak hache',       'GRAMME',     2.1500, 0.1900, 0.0000, 0.1500, 0.0000),
    ('frites surgelees',  'GRAMME',     1.5500, 0.0250, 0.2500, 0.0450, 0.0200),
    ('soupe',             'MILLILITRE', 0.3500, 0.0100, 0.0500, 0.0100, 0.0100);

-- =====================================================================
-- V3 : NORMAL
-- =====================================================================

INSERT INTO valeur_nutritionnelle_ingredient (ingredient_nom, unite, calories, proteines, glucides, lipides, fibres) VALUES
    ('croissant', 'UNITE', 270.0000, 5.5000, 27.0000, 15.0000, 1.5000),
    ('sucre', 'GRAMME', 4.0000, 0.0000, 1.0000, 0.0000, 0.0000),
    ('crepe', 'UNITE', 130.0000, 3.5000, 20.0000, 4.0000, 0.8000),
    ('fromage rape', 'GRAMME', 3.8000, 0.2700, 0.0050, 0.3000, 0.0000),
    ('biscotte', 'UNITE', 32.0000, 0.9000, 5.7000, 0.7000, 0.3000),
    ('chocolat en poudre', 'GRAMME', 3.8000, 0.0500, 0.8000, 0.0300, 0.0500),
    ('gaufre', 'UNITE', 180.0000, 4.0000, 25.0000, 7.0000, 1.0000),
    ('brioche', 'GRAMME', 3.7000, 0.0800, 0.5000, 0.1400, 0.0200),
    ('miel', 'GRAMME', 3.0400, 0.0030, 0.8200, 0.0000, 0.0020),
    ('pate a pizza', 'UNITE', 700.0000, 20.0000, 140.0000, 5.0000, 6.0000),
    ('pain de mie', 'GRAMME', 2.7000, 0.0800, 0.5000, 0.0350, 0.0250),
    ('lardons', 'GRAMME', 4.0000, 0.2400, 0.0000, 0.3400, 0.0000),
    ('creme fraiche', 'GRAMME', 3.0000, 0.0250, 0.0300, 0.3000, 0.0000),
    ('pommes de terre', 'GRAMME', 0.7700, 0.0200, 0.1700, 0.0010, 0.0220),
    ('semoule', 'GRAMME', 3.6000, 0.1250, 0.7200, 0.0110, 0.0350);

-- =====================================================================
-- V3 : HEALTHY
-- =====================================================================

INSERT INTO valeur_nutritionnelle_ingredient (ingredient_nom, unite, calories, proteines, glucides, lipides, fibres) VALUES
    ('flocons d''avoine', 'GRAMME', 3.7900, 0.1300, 0.6000, 0.0700, 0.1000),
    ('lait d''amande', 'MILLILITRE', 0.2400, 0.0050, 0.0300, 0.0150, 0.0030),
    ('fruits rouges', 'GRAMME', 0.5000, 0.0100, 0.1100, 0.0040, 0.0300),
    ('fromage blanc', 'GRAMME', 0.7500, 0.0800, 0.0400, 0.0300, 0.0000),
    ('avocat', 'UNITE', 240.0000, 3.0000, 12.0000, 22.0000, 10.0000),
    ('pain complet', 'GRAMME', 2.4500, 0.1000, 0.4100, 0.0350, 0.0700),
    ('epinards', 'GRAMME', 0.2300, 0.0290, 0.0360, 0.0040, 0.0220),
    ('graines de chia', 'GRAMME', 4.8600, 0.1700, 0.4200, 0.3100, 0.3400),
    ('quinoa', 'GRAMME', 3.6800, 0.1400, 0.6400, 0.0600, 0.0700),
    ('saumon', 'GRAMME', 2.0800, 0.2000, 0.0000, 0.1300, 0.0000),
    ('brocolis', 'GRAMME', 0.3400, 0.0280, 0.0700, 0.0040, 0.0260),
    ('lentilles', 'GRAMME', 3.5300, 0.2500, 0.6000, 0.0110, 0.1100),
    ('pois chiches', 'GRAMME', 3.6400, 0.1900, 0.6100, 0.0600, 0.1700),
    ('haricots verts', 'GRAMME', 0.3100, 0.0180, 0.0700, 0.0010, 0.0340),
    ('crevettes', 'GRAMME', 0.9900, 0.2100, 0.0020, 0.0100, 0.0000),
    ('miso', 'GRAMME', 1.9900, 0.1200, 0.2600, 0.0600, 0.0500),
    ('patate douce', 'GRAMME', 0.8600, 0.0160, 0.2000, 0.0010, 0.0300),
    ('concombre', 'GRAMME', 0.1500, 0.0070, 0.0360, 0.0010, 0.0050),
    ('houmous', 'GRAMME', 1.6600, 0.0800, 0.1400, 0.1000, 0.0600),
    ('the', 'GRAMME', 0.0100, 0.0000, 0.0030, 0.0000, 0.0000),
    ('fruits secs', 'GRAMME', 4.0000, 0.1000, 0.4000, 0.2500, 0.0800);

-- =====================================================================
-- V3 : GOURMAND
-- =====================================================================

INSERT INTO valeur_nutritionnelle_ingredient (ingredient_nom, unite, calories, proteines, glucides, lipides, fibres) VALUES
    ('pate feuilletee', 'UNITE', 780.0000, 10.0000, 65.0000, 52.0000, 3.0000),
    ('caramel beurre sale', 'GRAMME', 3.5000, 0.0100, 0.5500, 0.1400, 0.0000),
    ('chantilly', 'GRAMME', 3.0000, 0.0200, 0.0500, 0.3000, 0.0000),
    ('pralines roses', 'GRAMME', 4.5000, 0.0500, 0.6500, 0.1800, 0.0200),
    ('sirop d''erable', 'MILLILITRE', 2.6000, 0.0000, 0.6700, 0.0000, 0.0000),
    ('pommes', 'UNITE', 95.0000, 0.5000, 25.0000, 0.3000, 4.5000),
    ('boeuf', 'GRAMME', 2.5000, 0.2600, 0.0000, 0.1700, 0.0000),
    ('vin rouge', 'MILLILITRE', 0.8500, 0.0010, 0.0260, 0.0000, 0.0000),
    ('magret de canard', 'GRAMME', 2.8000, 0.1900, 0.0000, 0.2300, 0.0000),
    ('champignons', 'GRAMME', 0.2200, 0.0310, 0.0330, 0.0030, 0.0100),
    ('riz arborio', 'GRAMME', 3.5000, 0.0700, 0.7800, 0.0050, 0.0100),
    ('veau', 'GRAMME', 1.7200, 0.2000, 0.0000, 0.1000, 0.0000),
    ('cuisse de canard confite', 'UNITE', 550.0000, 30.0000, 0.0000, 47.0000, 0.0000),
    ('reblochon', 'GRAMME', 3.3000, 0.2000, 0.0050, 0.2700, 0.0000),
    ('saucisse fumee', 'GRAMME', 3.0000, 0.1300, 0.0200, 0.2700, 0.0000),
    ('choucroute', 'GRAMME', 0.1900, 0.0100, 0.0400, 0.0020, 0.0290),
    ('fromage a raclette', 'GRAMME', 3.3000, 0.2300, 0.0050, 0.2700, 0.0000),
    ('filet mignon', 'GRAMME', 1.4300, 0.2100, 0.0000, 0.0600, 0.0000),
    ('saint-jacques', 'GRAMME', 0.8800, 0.1700, 0.0300, 0.0080, 0.0000);

-- =====================================================================
-- V4 : diners (ingredients propres aux diners uniquement — les autres
-- reutilisent un couple ingredient/unite deja renseigne ci-dessus).
-- =====================================================================

INSERT INTO valeur_nutritionnelle_ingredient (ingredient_nom, unite, calories, proteines, glucides, lipides, fibres) VALUES
    ('poisson pane', 'UNITE', 220.0000, 12.0000, 18.0000, 11.0000, 1.0000),
    ('tortilla wrap', 'UNITE', 150.0000, 4.0000, 25.0000, 3.5000, 1.5000),
    ('courgette', 'GRAMME', 0.1700, 0.0120, 0.0310, 0.0030, 0.0100),
    ('lait de coco', 'MILLILITRE', 2.0000, 0.0200, 0.0300, 0.2000, 0.0000),
    ('tofu', 'GRAMME', 0.7600, 0.0800, 0.0190, 0.0480, 0.0120),
    ('feta', 'GRAMME', 2.6400, 0.1400, 0.0400, 0.2100, 0.0000),
    ('cabillaud', 'GRAMME', 0.8200, 0.1800, 0.0000, 0.0070, 0.0000),
    ('potiron', 'GRAMME', 0.2600, 0.0100, 0.0650, 0.0010, 0.0050),
    ('herbes de provence', 'GRAMME', 2.6000, 0.1000, 0.5500, 0.0500, 0.3500),
    ('cote de porc', 'GRAMME', 1.9500, 0.2000, 0.0000, 0.1300, 0.0000),
    ('moutarde', 'GRAMME', 0.6600, 0.0400, 0.0500, 0.0350, 0.0300),
    ('parmesan', 'GRAMME', 4.0000, 0.3500, 0.0090, 0.2900, 0.0000);
